=== amojs-xy/xml/basic_2/student.dtd
<!--
  + 允许多个
  * 0或多个
  ? 0或1个
    1个
  #PCDATA 纯文本
-->

<!ELEMENT students (student+)>
<!ELEMENT student (name,age,class,score)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT age (#PCDATA)>
<!ELEMENT class (#PCDATA)>
<!ELEMENT score (chinese,math,english)>
<!ELEMENT chinese (#PCDATA)>
<!ELEMENT math (#PCDATA)>
<!ELEMENT english (#PCDATA)>
<!ATTLIST student id CDATA "">
<!--
  ATTLIST 属性列表
student 标签名
id 属性名
CDATA 纯文本
"" 默认值
-->

=== amojs-xy/xml/basic_2/student.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!--<!DOCTYPE students SYSTEM "student.dtd">-->
<students>
    <student id="6666">
        <name>Mike</name>
        <age>18</age>
        <class>1</class>
        <score>
            <chinese>87</chinese>
            <math>77</math>
            <english>91</english>
        </score>
    </student>
    <student id="6667">
        <name>Rose</name>
        <age>17</age>
        <class>2</class>
        <score>
            <chinese>91</chinese>
            <math>92</math>
            <english>94</english>
        </score>
    </student>
</students>

<!--
  1. Idea检查
  2. Chrome浏览器验证
-->
