=== amojs-xy/xml/basic_2/student.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<schema
        xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.xml.com/xml-schema"
        elementFormDefault="qualified"
>
    <element name="students">
        <complexType>
            <sequence>
                <element name="student" minOccurs="1" maxOccurs="3">
                    <complexType>
                        <sequence>
                            <element name="name" type="string"/>
                            <element name="age">
                                <simpleType>
                                    <restriction base="integer">
                                        <minInclusive value="14"/>
                                        <maxInclusive value="20"/>
                                    </restriction>
                                </simpleType>
                            </element>
                            <element name="class">
                                <simpleType>
                                    <restriction base="integer">
                                        <minInclusive value="1"/>
                                        <maxInclusive value="10"/>
                                    </restriction>
                                </simpleType>
                            </element>
                            <element name="score">
                                <complexType>
                                    <sequence>
                                        <element name="chinese">
                                            <simpleType>
                                                <restriction base="integer">
                                                    <minInclusive value="0"/>
                                                    <maxInclusive value="100"/>
                                                </restriction>
                                            </simpleType>
                                                    </element>
                                                    <element name="math">
                                                        <simpleType>
                                                <restriction base="integer">
                                                    <minInclusive value="0"/>
                                                    <maxInclusive value="100"/>
                                                </restriction>
                                            </simpleType>
                                                    </element>
                                                    <element name="english">
                                                        <simpleType>
                                                <restriction base="integer">
                                                    <minInclusive value="0"/>
                                                    <maxInclusive value="100"/>
                                                </restriction>
                                            </simpleType>
                                        </element>
                                    </sequence>
                                </complexType>
                            </element>
                        </sequence>
                        <attribute name="id" type="string" use="required"/>
                    </complexType>
                </element>
            </sequence>
        </complexType>
    </element>
</schema>

=== amojs-xy/xml/basic_2/student-schema.xml
<?xml version="1.0" encoding="UTF-8" ?>
<students
        xmlns="http://www.xml.com/xml-schema"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://www.xml.com/xml-schema student.xsd"
>
    <student id="6666">
        <name>Mike</name>
        <age>18</age>
        <class>1</class>
        <score>
            <chinese>87</chinese>
            <math>77</math>
            <english>91</english>
        </score>
    </student>
    <student id="6667">
        <name>Rose</name>
        <age>17</age>
        <class>2</class>
        <score>
            <chinese>91</chinese>
            <math>92</math>
            <english>94</english>
        </score>
    </student>
</students>
